const CHARACTERS = [
    {  id: "kelsier", image: "images/kelsier.png", namesByDeck: { Scadrial: "Kelsier", Roshar: "Thaidakar", Shards: "Preservation" } },
    { id: "rashek", namesByDeck: { Scadrial: "Lord Ruler" }, image: "images/rashek.png" },
    { id: "mennis", namesByDeck: { Scadrial: "Mennis" } },
    { id: "vin", namesByDeck: { Scadrial: "Vin", Shards: "Preservation" }, image: "images/vin.png" },
    { id: "ulef", namesByDeck: { Scadrial: "Ulef" } },
    { id: "theron", namesByDeck: { Scadrial: "Theron" }, image: "images/theron.png" },
    { id: "camon", namesByDeck: { Scadrial: "Camon" }, image: "images/camon.png" },
    { id: "reen", namesByDeck: { Scadrial: "Reen" }, image: "images/reen.png" },
    { id: "dockson", namesByDeck: { Scadrial: "Dockson" }, image: "images/dockson.png" },
    { id: "milev", namesByDeck: { Scadrial: "Milev" } },
    { id: "ham", namesByDeck: { Scadrial: "Hammond" }, image: "images/ham.png" },
    { id: "breeze", namesByDeck: { Scadrial: "Breeze" }, image: "images/breeze.png" },
    { id: "clubs", namesByDeck: { Scadrial: "Clubs" }, image: "images/clubs.png" },
    { id: "yeden", namesByDeck: { Scadrial: "Yeden" }, image: "images/yeden.png" },
    { id: "marsh", namesByDeck: { Scadrial: "Marsh", Lumar: "Ironeyes" }, image: "images/marsh.png" },
    { id: "mare", namesByDeck: { Scadrial: "Mare" }, image: "images/mare.png" },
    { id: "spook", namesByDeck: { Scadrial: "Spook" }, image: "images/spook.png" },
    { id: "oreseur", namesByDeck: { Scadrial: "OreSeur" }, image: "images/oreseur.png" },
    { id: "straff", namesByDeck: { Scadrial: "Straff Venture" }, image: "images/straff.png" },
    { id: "sazed", namesByDeck: { Scadrial: "Sazed", Shards: "Harmony", Roshar: "Harmony", Emberdark: "Sazed" }, image: "images/sazed.png" },
    { id: "gemmel", namesByDeck: { Scadrial: "Gemmel" }, image: "images/gemmel.png" },
    { id: "elend", namesByDeck: { Scadrial: "Elend Venture" }, image: "images/elend.png" },
    { id: "melend", namesByDeck: { Scadrial: "Melend Liese" }, image: "images/melend.png" },
    { id: "shan", namesByDeck: { Scadrial: "Shan Elariel" }, image: "images/shan.png" },
    { id: "jastes", namesByDeck: { Scadrial: "Jastes Lekal" }, image: "images/jastes.png" },
    { id: "telden", namesByDeck: { Scadrial: "Telden Hasting" }, image: "images/telden.png" },
    { id: "hoid", namesByDeck: { Scadrial: "Hoid", Roshar: "Wit", Sel: "The Imperial Fool", Nalthis: "Hoid", Lumar: "Hoid", Yolen: "Midius", Worldhoppers: "Hoid", Komashi: "Coat rack", Canticle: "Hoid" }, image: "images/hoid.png" },
    { id: "demoux", namesByDeck: { Scadrial: "Demoux", Worldhoppers: "Demoux", Roshar: "Thinker" }, image: "images/demoux.png" },
    { id: "bilg", namesByDeck: { Scadrial: "Bilg" }, image: "images/bilg.png" },
    { id: "kliss", namesByDeck: { Scadrial: "Kliss" }, image: "images/kliss.png" },
    { id: "tensoon", namesByDeck: { Scadrial: "TenSoon" }, image: "images/tensoon.png" },
    { id: "kwaan", namesByDeck: { Scadrial: "Kwaan" }, image: "images/kwaan.png" },
    { id: "walin", namesByDeck: { Scadrial: "Walin" } },
    { id: "felt", namesByDeck: { Scadrial: "Felt", Roshar: "Felt", Worldhoppers: "Felt" } },
    { id: "bendal", namesByDeck: { Scadrial: "Bendal" }, image: "images/bendal.png" },
    { id: "goradel", namesByDeck: { Scadrial: "Goradel" }, image: "images/goradel.png" },
    { id: "kar", namesByDeck: { Scadrial: "Kar" }, image: "images/kar.png" },
    { id: "tevidian", namesByDeck: { Scadrial: "Tevidian Tekiel" }, image: "images/tevidian.png" },
    { id: "zane", namesByDeck: { Scadrial: "Zane Venture" }, image: "images/zane.png" },
    { id: "cett", namesByDeck: { Scadrial: "Ashweather Cett" }, image: "images/cett.png" },
    { id: "penrod", namesByDeck: { Scadrial: "Ferson Penrod" }, image: "images/penrod.png" },
    { id: "alendi", namesByDeck: { Scadrial: "Alendi" }, image: "images/alendi.png" },
    { id: "tindwyl", namesByDeck: { Scadrial: "Tindwyl" }, image: "images/tindwyl.png" },
    { id: "amaranta", namesByDeck: { Scadrial: "Amaranta" }, image: "images/amaranta.png" },
    { id: "allrianne", namesByDeck: { Scadrial: "Allrianne Cett" }, image: "images/allrianne.png" },
    { id: "gneorndin", namesByDeck: { Scadrial: "Gneorndin Cett" }, image: "images/gneorndin.png" },
    { id: "leras", namesByDeck: { Scadrial: "Preservation", Shards: "Preservation", Yolen: "Leras" }, image: "images/leras.png" },
    { id: "ati", namesByDeck: { Scadrial: "Ruin", Shards: "Ruin", Yolen: "Ati" }, image: "images/ati.png" },
    { id: "noorden", namesByDeck: { Scadrial: "Noorden" }, image: "images/noorden.png" },
    { id: "wellen", namesByDeck: { Scadrial: "Wellen" } },
    { id: "janarle", namesByDeck: { Scadrial: "General Janarle" }, image: "images/janarle.png" },
    { id: "fatren", namesByDeck: { Scadrial: "Fatren" } },
    { id: "human", namesByDeck: { Scadrial: "Human" }, image: "images/human.png" },
    { id: "kanpaar", namesByDeck: { Scadrial: "KanPaar" }, image: "images/kanpaar.png" },
    { id: "melaan", namesByDeck: { Scadrial: "MeLaan", Worldhoppers: "MeLaan" }, image: "images/melaan.png" },
    { id: "yomen", namesByDeck: { Scadrial: "Aradan Yomen" }, image: "images/yomen.png" },
    { id: "beldre", namesByDeck: { Scadrial: "Beldre" }, image: "images/beldre.png" },
    { id: "quellion", namesByDeck: { Scadrial: "Quellion" }, image: "images/quellion.png" },
    { id: "durn", namesByDeck: { Scadrial: "Durn" } },
    { id: "jedal", namesByDeck: { Scadrial: "Jedal" } },
    { id: "margel", namesByDeck: { Scadrial: "Margel" } },
    { id: "slowswift", namesByDeck: { Scadrial: "Slowswift" }, image: "images/slowswift.png" },
    { id: "autonomy", namesByDeck: { Taldain: "Autonomy", Scadrial: "Trell", Shards: "Autonomy", Yolen: "Bavadin", Roshar: "Bavadin", Emberdark: "Patji" } },
    { id: "haddek", namesByDeck: { Scadrial: "Haddek" } },
    { id: "spanky", namesByDeck: { Scadrial: "Spanky" }, image: "images/spanky.png" },
    { id: "khriss", namesByDeck: { Scadrial: "Khriss", Taldain: "Khrissalla", Worldhoppers: "Khriss" }, image: "images/khriss.png" },
    { id: "nazh", namesByDeck: { Threnody: "Nazh", Emberdark: "Nazh", Worldhoppers: "Nazh" }, image: "images/nazh.png" },
    { id: "adonalsium", namesByDeck: { Yolen: "Adonalsium", Scadrial: "Adonalsium", Roshar: "Adonalsium", Emberdark: "Adonalsium", Canticle: "Adonalsium" }, image: "images/adonalsium.png" },
    { id: "cultivation", namesByDeck: { Roshar: "Cultivation", Shards: "Cultivation", Yolen: "Koravellium Avast", Scadrial: "Cultivation" }, image: "images/kory.png" },
    { id: "devotion", namesByDeck: { Shards: "Devotion", Yolen: "Aona", Roshar: "Aona", Scadrial: "Devotion" }, image: "images/aona.png" },
    { id: "alonoe", namesByDeck: { Scadrial: "Alonoe", Worldhoppers: "Alonoe" }, image: "images/alonoe.png" },
    { id: "riina", namesByDeck: { Scadrial: "Riina", Lumar: "Sorceress", Worldhoppers: "Riina" }, image: "images/riina.png" },
    { id: "midge", namesByDeck: { Scadrial: "Midge" } },
    { id: "wax", namesByDeck: { Scadrial: "Waxillium Ladrian" }, image: "images/wax.png" },
    { id: "lessie", namesByDeck: { Scadrial: "Lessie" }, image: "images/lessie.png" },
    { id: "tan", namesByDeck: { Scadrial: "Bloody Tan" } },
    { id: "miles", namesByDeck: { Scadrial: "Miles Dagouter" }, image: "images/miles.png" },
    { id: "wayne", namesByDeck: { Scadrial: "Wayne" }, image: "images/wayne.png" },
    { id: "tillaume", namesByDeck: { Scadrial: "Tillaume" } },
    { id: "edwarn", namesByDeck: { Scadrial: "Edwarn Ladrian" }, image: "images/edwarn.png" },
    { id: "ranette", namesByDeck: { Scadrial: "Ranette" }, image: "images/ranette.png" },
    { id: "harms", namesByDeck: { Scadrial: "Jackstom Harms" } },
    { id: "steris", namesByDeck: { Scadrial: "Steris Harms" }, image: "images/steris.png" },
    { id: "marasi", namesByDeck: { Scadrial: "Marasi Colms" }, image: "images/marasi.png" },
    { id: "telsin", namesByDeck: { Scadrial: "Telsin Harms" }, image: "images/telsin.png" },
    { id: "peterus", namesByDeck: { Scadrial: "Peterus" } },
    { id: "tarson", namesByDeck: { Scadrial: "Tarson" }, image: "images/tarson.png" },
    { id: "deadfinger", namesByDeck: { Scadrial: "Jon Deadfinger" } },
    { id: "push", namesByDeck: { Scadrial: "Push" } },
    { id: "pull", namesByDeck: { Scadrial: "Pull" } },
    { id: "reddi", namesByDeck: { Scadrial: "Reddi" } },
    { id: "brettin", namesByDeck: { Scadrial: "Brettin" } },
    { id: "destroyer", namesByDeck: { Scadrial: "Destroyer" }, image: "images/destroyer.png" },
    { id: "joe", namesByDeck: { Scadrial: "Granite Joe" }, image: "images/granite.png" },
    { id: "winsting", namesByDeck: { Scadrial: "Winsting Innate" } },
    { id: "replar", namesByDeck: { Scadrial: "Replar Innate" } },
    { id: "idashwy", namesByDeck: { Scadrial: "Idashwy" } },
    { id: "marksman", namesByDeck: { Scadrial: "Marksman" }, image: "images/marksman.png" },
    { id: "bin", namesByDeck: { Scadrial: "Father Bin" } },
    { id: "aradel", namesByDeck: { Scadrial: "Claude Aradel" } },
    { id: "vwafendal", namesByDeck: { Scadrial: "Vwafendal" } },
    { id: "allriandre", namesByDeck: { Scadrial: "Allriandre" } },
    { id: "sophi", namesByDeck: { Scadrial: "Sophi Tarcsel" } },
    { id: "darriance", namesByDeck: { Scadrial: "Darriance" } },
    { id: "zobell", namesByDeck: { Scadrial: "ZoBell" } },
    { id: "drim", namesByDeck: { Scadrial: "Drim" } },
    { id: "larkspur", namesByDeck: { Scadrial: "Larkspur" } },
    { id: "johnst", namesByDeck: { Scadrial: "Johnst" } },
    { id: "chapaou", namesByDeck: { Scadrial: "Chapaou" } },
    { id: "migs", namesByDeck: { Scadrial: "Migs" } },
    { id: "forch", namesByDeck: { Scadrial: "Forch" } },
    { id: "vendell", namesByDeck: { Scadrial: "VenDell" }, image: "images/vendell.png" },
    { id: "reluur", namesByDeck: { Scadrial: "ReLuur" } },
    { id: "manton", namesByDeck: { Scadrial: "Ape Manton" }, image: "images/ape.png" },
    { id: "templeton", namesByDeck: { Scadrial: "Templeton Fig" } },
    { id: "kelesina", namesByDeck: { Scadrial: "Kelesina Shores" } },
    { id: "jak", namesByDeck: { Scadrial: "Allomancer Jak" }, image: "images/jak.png" },
    { id: "elizandra", namesByDeck: { Scadrial: "Elizandra Dramali" }, image: "images/elizandra.png" },
    { id: "handerwym", namesByDeck: { Scadrial: "Handerwym" } },
    { id: "sauvage", namesByDeck: { Scadrial: "Nicki Savage" }, image: "images/nicki.png" },
    { id: "irich", namesByDeck: { Scadrial: "Professor Irich" } },
    { id: "allik", namesByDeck: { Scadrial: "Allik Neverfar" }, image: "images/allik.png" },
    { id: "jordis", namesByDeck: { Scadrial: "Jordis" } },
    { id: "maxillium", namesByDeck: { Scadrial: "Maxillium Ladrian" }, image: "images/max.png" },
    { id: "tindwyll", namesByDeck: { Scadrial: "Tindwyl Ladrian" } },
    { id: "shailu", namesByDeck: { Scadrial: "Moonlight", Sel: "Shai", Worldhoppers: "Shai" }, image: "images/shai.png" },
    { id: "daal", namesByDeck: { Scadrial: "Admiral Daal" } },
    { id: "varlance", namesByDeck: { Scadrial: "Varlance" }, image: "images/varlance.png" },
    { id: "adawathwyn", namesByDeck: { Scadrial: "Adawathwyn" }, image: "images/adawathwyn.png" },
    { id: "ulaam", namesByDeck: { Scadrial: "Ulaam", Lumar: "Ulaam", Roshar: "Ulaam" }, image: "images/ulaam.png" },
    { id: "jaxy", namesByDeck: { Scadrial: "Jaxy" }, image: "images/jaxy.png" },
    { id: "odium", namesByDeck: { Scadrial: "Odium", Roshar: "Odium", Shards: "Odium", Yolen: "Rayse" }, image: "images/rayse.png" },
    { id: "getruda", namesByDeck: { Scadrial: "Getruda" }, image: "images/getruda.png" },
    { id: "dumad", namesByDeck: { Scadrial: "Dumad" }, image: "images/dumad.png" },
    { id: "gave", namesByDeck: { Scadrial: "Gave Entrone" } },
    { id: "maraga", namesByDeck: { Scadrial: "Maraga Dulcet" } },
    { id: "whimsy", namesByDeck: { Scadrial: "Whimsy", Roshar: "Whimsy", Shards: "Whimsy" } },
    { id: "kaise", namesByDeck: { Scadrial: "Codenames Are Stupid", Sel: "Kaise", Worldhoppers: "Kaise" }, image: "images/kaise.png" },
    { id: "twinsoul", namesByDeck: { Scadrial: "Twinsoul", Worldhoppers: "Twinsoul" }, image: "images/twinsoul.png" },
    { id: "silajana", namesByDeck: { Scadrial: "Silajana", Worldhoppers: "Silajana" }, image: "images/silajana.png" },
    { id: "dao", namesByDeck: { Scadrial: "Dao", Sel: "Dao", Worldhoppers: "Dao" }, image: "images/dao.png" },
    { id: "kyndlip", namesByDeck: { Scadrial: "Kyndlip Turnavyl" } },
    { id: "armal", namesByDeck: { Scadrial: "Armal Harms" } },
    { id: "wellid", namesByDeck: { Scadrial: "Wellid" } },
    { id: "ruri", namesByDeck: { Scadrial: "Ruri" } },
    { id: "garisel", namesByDeck: { Scadrial: "Garisel Daring" } },
    { id: "call", namesByDeck: { Scadrial: "Mister Call" } },
    { id: "janven", namesByDeck: { Scadrial: "Jan Ven", Worldhoppers: "Jan Ven" }, image: "images/janven.png" },

    { id: "raoden", namesByDeck: { Sel: "Raoden" }, image: "images/raoden.png" },
    { id: "iadon", namesByDeck: { Sel: "Iadon" }, image: "images/iadon.png" },
    { id: "galladon", namesByDeck: { Sel: "Galladon", Worldhoppers: "Galladon", Roshar: "Grump" }, image: "images/galladon.png" },
    { id: "ien", namesByDeck: { Sel: "Ien" } },
    { id: "sarene", namesByDeck: { Sel: "Sarene" }, image: "images/sarene.png" },
    { id: "ashe", namesByDeck: { Sel: "Ashe" } },
    { id: "eshen", namesByDeck: { Sel: "Queen Eshen" } },
    { id: "eventeo", namesByDeck: { Sel: "King Eventeo" } },
    { id: "wyrn", namesByDeck: { Sel: "Wyrn" } },
    { id: "hrathen", namesByDeck: { Sel: "Hrathen" }, image: "images/hrathen.png" },
    { id: "dilaf", namesByDeck: { Sel: "Dilaf" }, image: "images/dilaf.png" },
    { id: "fjon", namesByDeck: { Sel: "Fjon" } },
    { id: "riino", namesByDeck: { Sel: "Riino", Worldhoppers: "Riino", Roshar: "Oracle" } },
    { id: "shaor", namesByDeck: { Sel: "Shaor" } },
    { id: "aanden", namesByDeck: { Sel: "Taan" } },
    { id: "karata", namesByDeck: { Sel: "Karata" }, image: "images/karata.png" },
    { id: "kiin", namesByDeck: { Sel: "Kiin" }, image: "images/kiin.png" },
    { id: "roial", namesByDeck: { Sel: "Duke Roial" }, image: "images/roial.png" },
    { id: "lukel", namesByDeck: { Sel: "Lukel" }, image: "images/lukel.png" },
    { id: "jalla", namesByDeck: { Sel: "Jalla" } },
    { id: "daora", namesByDeck: { Sel: "Daora" } },
    { id: "daorn", namesByDeck: { Sel: "Daorn" } },
    { id: "adien", namesByDeck: { Sel: "Adien" } },
    { id: "mareshe", namesByDeck: { Sel: "Mareshe" } },
    { id: "telrii", namesByDeck: { Sel: "Telrii" }, image: "images/telrii.png" },
    { id: "saolin", namesByDeck: { Sel: "Saolin" } },
    { id: "eondel", namesByDeck: { Sel: "Eondel" } },
    { id: "shuden", namesByDeck: { Sel: "Shuden" }, image: "images/shuden.png" },
    { id: "ahan", namesByDeck: { Sel: "Count Ahan" } },
    { id: "edan", namesByDeck: { Sel: "Edan" } },
    { id: "kahar", namesByDeck: { Sel: "Kahar" } },
    { id: "torena", namesByDeck: { Sel: "Torena" } },
    { id: "dashe", namesByDeck: { Sel: "Dashe" } },
    { id: "omin", namesByDeck: { Sel: "Father Omin" } },
    { id: "seinalan", namesByDeck: { Sel: "Seinalan" } },
    { id: "forton", namesByDeck: { Sel: "Forton" } },
    { id: "matisse", namesByDeck: { Sel: "Matisse" } },
    { id: "gaotana", namesByDeck: { Sel: "Gaotana" } },
    { id: "frava", namesByDeck: { Sel: "Frava" } },
    { id: "zu", namesByDeck: { Sel: "Zu" } },
    { id: "ashravan", namesByDeck: { Sel: "Ashravan" } },
    { id: "weedfingers", namesByDeck: { Sel: "Weedfingers" } },
    { id: "shuxen", namesByDeck: { Sel: "Han ShuXen" } },

    { id: "kalak", namesByDeck: { Roshar: "Kalak" }, image: "images/kalak.png" },
    { id: "jezrien", namesByDeck: { Roshar: "Jezrien" }, image: "images/jezrien.png" },
    { id: "taln", namesByDeck: { Roshar: "Taln" }, image: "images/taln.png" },
    { id: "ishar", namesByDeck: { Roshar: "Ishar" }, image: "images/ishar.png" },
    { id: "szeth", namesByDeck: { Roshar: "Szeth, Truthless" }, image: "images/szeth.png" },
    { id: "dalinar", namesByDeck: { Roshar: "Dalinar Kholin" }, image: "images/dalinar.png" },
    { id: "elhokar", namesByDeck: { Roshar: "Elhokar Kholin" }, image: "images/elhokar.png" },
    { id: "sadeas", namesByDeck: { Roshar: "Torol Sadeas" } },
    { id: "gavilar", namesByDeck: { Roshar: "Gavilar Kholin" } },
    { id: "jasnah", namesByDeck: { Roshar: "Jasnah Kholin" }, image: "images/jasnah.png" },
    { id: "shalash", namesByDeck: { Roshar: "Shalash" }, image: "images/shalash.png" },
    { id: "cenn", namesByDeck: { Roshar: "Cenn" } },
    { id: "amaram", namesByDeck: { Roshar: "Meridas Amaram" }, image: "images/amaram.png" },
    { id: "kaladin", namesByDeck: { Roshar: "Kaladin Stormblessed" }, image: "images/kaladin.png" },
    { id: "tvlakv", namesByDeck: { Roshar: "Tvlakv" } },
    { id: "helaran", namesByDeck: { Roshar: "Helaran Davar" } },
    { id: "syl", namesByDeck: { Roshar: "Sylphrena" }, image: "images/syl.png" },
    { id: "lirin", namesByDeck: { Roshar: "Lirin" }, image: "images/lirin.png" },
    { id: "tien", namesByDeck: { Roshar: "Tien" } },
    { id: "shallan", namesByDeck: { Roshar: "Shallan Davar" }, image: "images/shallan.png" },
    { id: "tozbek", namesByDeck: { Roshar: "Captain Tozbek" } },
    { id: "jushu", namesByDeck: { Roshar: "Asha Jushu Davar" } },
    { id: "yalb", namesByDeck: { Roshar: "Yalb" } },
    { id: "lin", namesByDeck: { Roshar: "Lin Davar" } },
    { id: "tag", namesByDeck: { Roshar: "Tag" } },
    { id: "roshone", namesByDeck: { Roshar: "Toralin Roshone" } },
    { id: "taravangian", namesByDeck: { Roshar: "Taravangian", Shards: "Retribution" } },
    { id: "nohadon", namesByDeck: { Roshar: "Nohadon" } },
    { id: "hashal", namesByDeck: { Roshar: "Hashal" } },
    { id: "hesina", namesByDeck: { Roshar: "Hesina" }, image: "images/hesina.png" },
    { id: "matal", namesByDeck: { Roshar: "Avarak Matal" } },
    { id: "gaz", namesByDeck: { Roshar: "Gaz" } },
    { id: "laral", namesByDeck: { Roshar: "Laral Roshone" } },
    { id: "lamaril", namesByDeck: { Roshar: "Lamaril" } },
    { id: "kabsal", namesByDeck: { Roshar: "Kabsal" } },
    { id: "balat", namesByDeck: { Roshar: "Balat Davar" } },
    { id: "wikim", namesByDeck: { Roshar: "Wikim Davar" } },
    { id: "teft", namesByDeck: { Roshar: "Teft" }, image: "images/teft.png" },
    { id: "ishikk", namesByDeck: { Roshar: "Ishikk" } },
    { id: "eylita", namesByDeck: { Roshar: "Eylita Tavinar" } },
    { id: "nightwatcher", namesByDeck: { Roshar: "Nightwatcher" } },
    { id: "adolin", namesByDeck: { Roshar: "Adolin Kholin" }, image: "images/adolin.png" },
    { id: "nergaoul", namesByDeck: { Roshar: "Nergaoul" } },
    { id: "renarin", namesByDeck: { Roshar: "Renarin Kholin" }, image: "images/renarin.png" },
    { id: "gallant", namesByDeck: { Roshar: "Gallant" } },
    { id: "bashin", namesByDeck: { Roshar: "Bashin" } },
    { id: "janala", namesByDeck: { Roshar: "Janala Lustow" } },
    { id: "honor", namesByDeck: { Roshar: "Almighty", Shards: "Honor", Yolen: "Tanavast" }, image: "images/tanavast.png" },
    { id: "navani", namesByDeck: { Roshar: "Navani Kholin" }, image: "images/navani.png" },
    { id: "sureblood", namesByDeck: { Roshar: "Sureblood" } },
    { id: "moash", namesByDeck: { Roshar: "Moash" }, image: "images/moash.png" },
    { id: "dunny", namesByDeck: { Roshar: "Dunny" } },
    { id: "sigzil", namesByDeck: { Roshar: "Sigzil", Canticle: "Nomad", Worldhoppers: "Zellion" }, image: "images/sigzil.png" },
    { id: "leyten", namesByDeck: { Roshar: "Leyten" } },
    { id: "rock", namesByDeck: { Roshar: "Numuhukumakiaki'aialunamor - Rock" }, image: "images/rock.png" },
    { id: "vamah", namesByDeck: { Roshar: "Loradar Vamah" } },
    { id: "evi", namesByDeck: { Roshar: "Shshshshshshs - Evi" }, image: "images/evi.png" },
    { id: "roion", namesByDeck: { Roshar: "Roion" } },
    { id: "jost", namesByDeck: { Roshar: "Jost" } },
    { id: "wistiow", namesByDeck: { Roshar: "Wistiow" } },
    { id: "drehy", namesByDeck: { Roshar: "Drehy" }, image: "images/drehy.png" },
    { id: "hobber", namesByDeck: { Roshar: "Hobber" } },
    { id: "dabbid", namesByDeck: { Roshar: "Dabbid" } },
    { id: "teshav", namesByDeck: { Roshar: "Teshav Khal" } },
    { id: "khal", namesByDeck: { Roshar: "General Khal" } },
    { id: "kadash", namesByDeck: { Roshar: "Kadash" } },
    { id: "aladar", namesByDeck: { Roshar: "Aladar" } },
    { id: "re-shephir", namesByDeck: { Roshar: "Re-Shephir" } },
    { id: "dominion", namesByDeck: { Roshar: "Skai", Shards: "Dominion", Yolen: "Skai", Emberdark: "Dominion" } },
    { id: "jaks", namesByDeck: { Roshar: "Earless Jaks" } },
    { id: "natam", namesByDeck: { Roshar: "Natam" } },
    { id: "skar", namesByDeck: { Roshar: "Skar" }, image: "images/skar.png" },
    { id: "sadees", namesByDeck: { Roshar: "Sadees Sunmaker" } },
    { id: "teleb", namesByDeck: { Roshar: "Teleb" } },
    { id: "peet", namesByDeck: { Roshar: "Peet" } },
    { id: "nale", namesByDeck: { Roshar: "Nale" }, image: "images/shalash.png" },
    { id: "danlan", namesByDeck: { Roshar: "Danlan Morakotha" } },
    { id: "rysn", namesByDeck: { Roshar: "Rysn Ftori bah-Vstim" }, image: "images/rysn.png" },
    { id: "vstim", namesByDeck: { Roshar: "Vstim" } },
    { id: "thresh", namesByDeck: { Roshar: "Thresh-son-Esan" } },
    { id: "axies", namesByDeck: { Roshar: "Axies the Collector" }, image: "images/axies.png" },
    { id: "cusicesh", namesByDeck: { Roshar: "Cusicesh the Protector", Worldhoppers: "Cusicesh the Protector" } },
    { id: "neturo", namesByDeck: { Roshar: "Neturo-son-Vallano" } },
    { id: "luesh", namesByDeck: { Roshar: "Luesh" } },
    { id: "bisig", namesByDeck: { Roshar: "Bisig" } },
    { id: "lopen", namesByDeck: { Roshar: "The Lopen" } },
    { id: "stormfather", namesByDeck: { Roshar: "Stormfather" } },
    { id: "rillir", namesByDeck: { Roshar: "Rillir Roshone" } },
    { id: "ashlv", namesByDeck: { Roshar: "Ashlv" } },
    { id: "blightwind", namesByDeck: { Roshar: "Yelig-nar" } },
    { id: "rlain", namesByDeck: { Roshar: "Rlain" }, image: "images/rlain.png" },
    { id: "baxil", namesByDeck: { Roshar: "Baxil" } },
    { id: "av", namesByDeck: { Roshar: "Av" } },
    { id: "geranid", namesByDeck: { Roshar: "Geranid" } },
    { id: "ashir", namesByDeck: { Roshar: "Ashir" } },
    { id: "jakamav", namesByDeck: { Roshar: "Jakamav" } },
    { id: "inkima", namesByDeck: { Roshar: "Inkima" } },
    { id: "tarah", namesByDeck: { Roshar: "Tarah" } },
    { id: "eshonai", namesByDeck: { Roshar: "Eshonai" }, image: "images/eshonai.png" },
    { id: "pattern", namesByDeck: { Roshar: "Pattern" } },
    { id: "aesudan", namesByDeck: { Roshar: "Aesudan Kholin" } },
    { id: "liss", namesByDeck: { Roshar: "Liss the Weeper" } },
    { id: "gangnah", namesByDeck: { Roshar: "Gangnah" } },
    { id: "varnali", namesByDeck: { Roshar: "Varnali" } },
    { id: "ivory", namesByDeck: { Roshar: "Ivory" } },
    { id: "klade", namesByDeck: { Roshar: "Klade" } },
    { id: "rushu", namesByDeck: { Roshar: "Rushu" } },
    { id: "taker", namesByDeck: { Roshar: "Sja-anat" } },
    { id: "ialai", namesByDeck: { Roshar: "Ialai Sadeas" }, image: "images/sadeas.png" },
    { id: "chanarach", namesByDeck: { Roshar: "Chanarach" }, image: "images/chanarach.png" },
    { id: "testament", namesByDeck: { Roshar: "Testament" } },
    { id: "stick", namesByDeck: { Roshar: "Stick" } },
    { id: "demid", namesByDeck: { Roshar: "Demid" } },
    { id: "venli", namesByDeck: { Roshar: "Venli" }, image: "images/venli.png" },
    { id: "ym", namesByDeck: { Roshar: "Ym" } },
    { id: "relu", namesByDeck: { Roshar: "Relu-na" } },
    { id: "talik", namesByDeck: { Roshar: "Talik" } },
    { id: "ral", namesByDeck: { Roshar: "Ral-na" } },
    { id: "chiri", namesByDeck: { Roshar: "Chiri-Chiri" } },
    { id: "thude", namesByDeck: { Roshar: "Thude" } },
    { id: "bila", namesByDeck: { Roshar: "Bila" } },
    { id: "jaxlim", namesByDeck: { Roshar: "Jaxlim" } },
    { id: "vasher", namesByDeck: { Roshar: "Zahel", Nalthis: "Vasher", Worldhoppers: "Vasher" }, image: "images/vasher.png" },
    { id: "tyn", namesByDeck: { Roshar: "Tyn" } },
    { id: "vathah", namesByDeck: { Roshar: "Vathah" } },
    { id: "punio", namesByDeck: { Roshar: "Punio" } },
    { id: "red", namesByDeck: { Roshar: "Red" } },
    { id: "jenet", namesByDeck: { Roshar: "Jenet" } },
    { id: "vedel", namesByDeck: { Roshar: "Vedel" }, image: "images/vedel.png" },
    { id: "sebarial", namesByDeck: { Roshar: "Turinad Sebarial" } },
    { id: "redin", namesByDeck: { Roshar: "Redin" } },
    { id: "malise", namesByDeck: { Roshar: "Malise Gevelmar" } },
    { id: "palona", namesByDeck: { Roshar: "Palona" } },
    { id: "iyatil", namesByDeck: { Roshar: "Iyatil", Worldhoppers: "Iyatil" } },
    { id: "mraize", namesByDeck: { Roshar: "Mraize" } },
    { id: "jeksonofnone", namesByDeck: { Roshar: "Jeksonofnone" } },
    { id: "dreder", namesByDeck: { Roshar: "Dreder" } },
    { id: "huio", namesByDeck: { Roshar: "Huio", Worldhoppers: "Huio" } },
    { id: "gavinor", namesByDeck: { Roshar: "Gavinor Kholin" }, image: "images/gavinor.png" },
    { id: "inadara", namesByDeck: { Roshar: "Inadara" } },
    { id: "lift", namesByDeck: { Roshar: "Lift" }, image: "images/lift.png" },
    { id: "gawx", namesByDeck: { Roshar: "Gawx - Yanagawn the First" } },
    { id: "wyndle", namesByDeck: { Roshar: "Wyndle" } },
    { id: "timbre", namesByDeck: { Roshar: "Timbre" } },
    { id: "lhan", namesByDeck: { Roshar: "Lhan" } },
    { id: "pai", namesByDeck: { Roshar: "Pai" } },
    { id: "mrall", namesByDeck: { Roshar: "Mrall" } },
    { id: "adrotagia", namesByDeck: { Roshar: "Adrotagia" } },
    { id: "batar", namesByDeck: { Roshar: "Battar" }, image: "images/battar.png" },
    { id: "moelach", namesByDeck: { Roshar: "Moelach" } },
    { id: "lyn", namesByDeck: { Roshar: "Lyn" }, image: "images/lyn.png" },
    { id: "nightblood", namesByDeck: { Roshar: "Sword-nimi", Nalthis: "Nightblood", Worldhoppers: "Nightblood" } },
    { id: "glys", namesByDeck: { Roshar: "Glys" } },
    { id: "maladar", namesByDeck: { Roshar: "May Aladar" } },
    { id: "oroden", namesByDeck: { Roshar: "Oroden" }, image: "images/oroden.png" },
    { id: "tanalan", namesByDeck: { Roshar: "Tanalan" } },
    { id: "rnamdi", namesByDeck: { Roshar: "Queen Fen" }, image: "images/fen.png" },
    { id: "sah", namesByDeck: { Roshar: "Sah" } },
    { id: "khen", namesByDeck: { Roshar: "Khen" } },
    { id: "toh", namesByDeck: { Roshar: "Toh" } },
    { id: "vai", namesByDeck: { Roshar: "Vai" } },
    { id: "ishnah", namesByDeck: { Roshar: "Ishnah" } },
    { id: "betha", namesByDeck: { Roshar: "Betha" } },
    { id: "malata", namesByDeck: { Roshar: "Malata" } },
    { id: "spark", namesByDeck: { Roshar: "Spark" } },
    { id: "shob", namesByDeck: { Roshar: "Shob" } },
    { id: "cabine", namesByDeck: { Roshar: "Cabine" } },
    { id: "eshu", namesByDeck: { Roshar: "Eshu" } },
    { id: "dilid", namesByDeck: { Roshar: "Dilid" } },
    { id: "puuli", namesByDeck: { Roshar: "Puuli" } },
    { id: "ellista", namesByDeck: { Roshar: "Ellista" } },
    { id: "urv", namesByDeck: { Roshar: "Urv" } },
    { id: "ulim", namesByDeck: { Roshar: "Ulim" } },
    { id: "phendorana", namesByDeck: { Roshar: "Phendorana" }, image: "images/phendorana.png" },
    { id: "song", namesByDeck: { Roshar: "Song - Tuaka'li'na'calmi'nor" } },
    { id: "gift", namesByDeck: { Roshar: "Gift" } },
    { id: "cord", namesByDeck: { Roshar: "Cord - Hualinam’lunanaki’akilu" } },
    { id: "star", namesByDeck: { Roshar: "Star" } },
    { id: "kumatiki", namesByDeck: { Roshar: "Kuma'tiki" } },
    { id: "beautifulsong", namesByDeck: { Roshar: "Beautiful Song" } },
    { id: "rockjr", namesByDeck: { Roshar: "Rock Jr." } },
    { id: "ristina", namesByDeck: { Roshar: "Ristina" } },
    { id: "falilar", namesByDeck: { Roshar: "Falilar" } },
    { id: "da", namesByDeck: { Roshar: "Da" } },
    { id: "kaza", namesByDeck: { Roshar: "Kaza" } },
    { id: "hariel", namesByDeck: { Roshar: "Hariel" } },
    { id: "kmakl", namesByDeck: { Roshar: "Kmakl" } },
    { id: "kdralk", namesByDeck: { Roshar: "Kdralk" } },
    { id: "vivenna", namesByDeck: { Roshar: "Azure", Nalthis: "Vivenna", Worldhoppers: "Vivenna" }, image: "images/vivenna.png" },
    { id: "noura", namesByDeck: { Roshar: "Noura" } },
    { id: "tsa", namesByDeck: { Roshar: "Queen Tsa" } },
    { id: "ashertmarn", namesByDeck: { Roshar: "Ashertmarn" } },
    { id: "noromin", namesByDeck: { Roshar: "Noromin" } },
    { id: "beard", namesByDeck: { Roshar: "Beard" } },
    { id: "alward", namesByDeck: { Roshar: "Alward" } },
    { id: "hid", namesByDeck: { Roshar: "Hid" } },
    { id: "hadinar", namesByDeck: { Roshar: "Hadinar" } },
    { id: "vaceslv", namesByDeck: { Roshar: "Vaceslv" } },
    { id: "vardinar", namesByDeck: { Roshar: "Vardinar" } },
    { id: "ved", namesByDeck: { Roshar: "Ved" } },
    { id: "nananav", namesByDeck: { Roshar: "Nananav" } },
    { id: "grund", namesByDeck: { Roshar: "Grund" } },
    { id: "mayalaran", namesByDeck: { Roshar: "Mayalaran" } },
    { id: "mem", namesByDeck: { Roshar: "Mem" } },
    { id: "sheler", namesByDeck: { Roshar: "Sheler" } },
    { id: "dieno", namesByDeck: { Roshar: "Dieno the Mink" } },
    { id: "dai-gonarthis", namesByDeck: { Roshar: "Dai-Gonarthis" } },
    { id: "ki", namesByDeck: { Roshar: "Ki" } },
    { id: "shashara", namesByDeck: { Roshar: "Shashara", Nalthis: "Shashara", Worldhoppers: "Glorysinger" } },
    { id: "joret", namesByDeck: { Roshar: "Joret" } },
    { id: "ty", namesByDeck: { Roshar: "Ty" } },
    { id: "denth", namesByDeck: { Roshar: "VaraTreledees", Nalthis: "Denth", Worldhoppers: "Denth" }, image: "images/denth.png" },
    { id: "ico", namesByDeck: { Roshar: "Ico" } },
    { id: "notum", namesByDeck: { Roshar: "Notum" } },
    { id: "malli", namesByDeck: { Roshar: "Malli", Worldhoppers: "Malli" } },
    { id: "yushah", namesByDeck: { Roshar: "Yushah" } },
    { id: "kara", namesByDeck: { Roshar: "Kara" } },
    { id: "hnanan", namesByDeck: { Roshar: "Hnanan" } },
    { id: "design", namesByDeck: { Roshar: "Design", Worldhoppers: "Design", Lumar: "Design", Emberdark: "Design", Komashi: "Design" } },
    { id: "gereh", namesByDeck: { Roshar: "Gereh" } },
    { id: "noril", namesByDeck: { Roshar: "Noril" } },
    { id: "lezian", namesByDeck: { Roshar: "Lezian the Pursuer" } },
    { id: "sibling", namesByDeck: { Roshar: "Sibling" } },
    { id: "godeke", namesByDeck: { Roshar: "Godeke" } },
    { id: "beryl", namesByDeck: { Roshar: "Beryl" } },
    { id: "raboniel", namesByDeck: { Roshar: "Raboniel" } },
    { id: "endowment", namesByDeck: { Roshar: "Endowment", Nalthis: "Endowment", Shards: "Endowment", Yolen: "Edgli" } },
    { id: "rua", namesByDeck: { Roshar: "Rua" } },
    { id: "tumi", namesByDeck: { Roshar: "Tumi" } },
    { id: "mishram", namesByDeck: { Roshar: "Ba-Ado-Mishram" } },
    { id: "stargyl", namesByDeck: { Roshar: "Stargyle" } },
    { id: "zur", namesByDeck: { Roshar: "Zu" } },
    { id: "arshqqam", namesByDeck: { Roshar: "Arshqqam the Stump" } },
    { id: "dreaming", namesByDeck: { Roshar: "Dreaming-though-Awake" } },
    { id: "uapam", namesByDeck: { Roshar: "Ua’pam" } },
    { id: "adin", namesByDeck: { Roshar: "Adin" } },
    { id: "kuno", namesByDeck: { Roshar: "Kuno" } },
    { id: "teofil", namesByDeck: { Roshar: "Teofil" } },
    { id: "lyon", namesByDeck: { Roshar: "Commander Lyon" } },
    { id: "melishi", namesByDeck: { Roshar: "Melishi" } },
    { id: "ulvlk", namesByDeck: { Roshar: "Ulvlk" } },
    { id: "axindweth", namesByDeck: { Roshar: "Axindweth", Worldhoppers: "Axindweth" } },
    { id: "essu", namesByDeck: { Roshar: "Essu" } },
    { id: "auxiliary", namesByDeck: { Roshar: "12124", Worldhoppers: "Aux", Canticle: "Auxiliary" } },
    { id: "sixteen", namesByDeck: { Roshar: "Sixteen", Worldhoppers: "Sixteen" } },
    { id: "blended", namesByDeck: { Roshar: "Blended" } },
    { id: "lusintia", namesByDeck: { Roshar: "Lusintia" } },
    { id: "sekeir", namesByDeck: { Roshar: "Sekeir" } },
    { id: "amuna", namesByDeck: { Roshar: "Amuna" } },
    { id: "riah", namesByDeck: { Roshar: "Riah" } },
    { id: "ala", namesByDeck: { Roshar: "Ala", Worldhoppers: "Ala" } },
    { id: "el", namesByDeck: { Roshar: "El" } },
    { id: "wind", namesByDeck: { Roshar: "Wind" } },
    { id: "dami", namesByDeck: { Roshar: "Dami" } },
    { id: "vienta", namesByDeck: { Roshar: "Vienta" } },
    { id: "abidi", namesByDeck: { Roshar: "Abidi" } },
    { id: "frost", namesByDeck: { Roshar: "Frost", Worldhoppers: "Frost", Emberdark: "Frost", Yolen: "Frost" } },
    { id: "night", namesByDeck: { Roshar: "Night" } },
    { id: "stone", namesByDeck: { Roshar: "Stone" } },
    { id: "molli", namesByDeck: { Roshar: "Molli" } },
    { id: "elid", namesByDeck: { Roshar: "Elid-daughter-Zeenid" } },
    { id: "zeenid", namesByDeck: { Roshar: "Zeenid-daughter-Beth" } },
    { id: "isasik", namesByDeck: { Roshar: "Isasik" } },
    { id: "breteh", namesByDeck: { Roshar: "Breteh" } },
    { id: "valor", namesByDeck: { Roshar: "Valor", Shards: "Valor", Yolen: "Medelantorius" } },
    { id: "zarb", namesByDeck: { Roshar: "Zarb Kushkam" } },
    { id: "yesteel", namesByDeck: { Roshar: "Yesteel", Nalthis: "Yesteel", Worldhoppers: "Yesteel" } },
    { id: "kaminah", namesByDeck: { Roshar: "Kaminah" } },
    { id: "rahel", namesByDeck: { Roshar: "Rahel" } },
    { id: "rit", namesByDeck: { Roshar: "Rit-daughter-Clutio" } },
    { id: "hmask", namesByDeck: { Roshar: "Hmask" } },
    { id: "sivi", namesByDeck: { Roshar: "Sivi-daughter-Sivi" } },
    { id: "neziham", namesByDeck: { Roshar: "Neziham" } },
    { id: "gezemal", namesByDeck: { Roshar: "Gezamal Kushkam" } },
    { id: "pozen", namesByDeck: { Roshar: "Pozen-son-Nash" } },
    { id: "oathbringer", namesByDeck: { Roshar: "Oathbringer" } },
    { id: "dulo", namesByDeck: { Roshar: "Dulo-son-Tudla" } },
    { id: "elodi", namesByDeck: { Roshar: "Elodi" } },
    { id: "makibak", namesByDeck: { Roshar: "Makibak" } },
    { id: "pralla", namesByDeck: { Roshar: "Pralla" }, image: "images/pralla.png" },
    { id: "zabra", namesByDeck: { Roshar: "Zabra" } },
    { id: "fleet", namesByDeck: { Roshar: "Fleet" } },
    { id: "vambra", namesByDeck: { Roshar: "Vambra-daughter-Skies" } },
    { id: "thundercloud", namesByDeck: { Roshar: "Thundercloud" } },
    { id: "moss", namesByDeck: { Roshar: "Moss-son-Farrier" } },
    { id: "garith", namesByDeck: { Roshar: "Garith" } },
    { id: "dyel", namesByDeck: { Roshar: "Dyel", Worldhoppers: "Dyel" } },
    { id: "terushal", namesByDeck: { Roshar: "Terushal" } },
    { id: "shmone", namesByDeck: { Roshar: "Shmone" } },
    { id: "121", namesByDeck: { Roshar: "121" } },
    { id: "nikliasorm", namesByDeck: { Roshar: "Nikliasorm" }, image: "images/nikli.png" },
    { id: "alalhawithador", namesByDeck: { Roshar: "Alalhawithador" } },
    { id: "ambition", namesByDeck: { Roshar: "Ambition", Shards: "Ambition", Threnody: "Evil", Yolen: "Uli Da", Emberdark: "Type 1-6 Threnodite entity" } },
    { id: "reason", namesByDeck: { Roshar: "Reason", Shards: "Reason", Yolen: "Euridius" } },
    { id: "invention", namesByDeck: { Roshar: "Invention", Shards: "Invention", Yolen: "Chan Ko Sar", Emberdark: "Invention" } },
    { id: "mercy", namesByDeck: { Roshar: "Mercy", Shards: "Mercy", Yolen: "Mercy" } },
    { id: "skyblue", namesByDeck: { Roshar: "Skyblue" } },
    { id: "billid", namesByDeck: { Roshar: "Billid" } },
    { id: "xorm", namesByDeck: { Roshar: "Xorm" } },
    { id: "hauka", namesByDeck: { Roshar: "Hauka" } },
    { id: "mik", namesByDeck: { Roshar: "Mik" } },
    { id: "arclomedarian", namesByDeck: { Roshar: "Arclomedarian" } },
    { id: "tiqqa", namesByDeck: { Roshar: "Tiqqa" } },
    { id: "drlwan", namesByDeck: { Roshar: "Drlwan" } },
    { id: "kstled", namesByDeck: { Roshar: "Kstled" } },
    { id: "yelamaiszin", namesByDeck: { Roshar: "Yelamaiszin" } },
    { id: "zyardil", namesByDeck: { Roshar: "Zyardil" } },
    { id: "caelinora", namesByDeck: { Roshar: "Caelinora" } },
    { id: "screech", namesByDeck: { Roshar: "Screech" } },
    { id: "jerick", namesByDeck: { Yolen: "Jerick" } },

    { id: "kenton", namesByDeck: { Taldain: "Kenton" } },
    { id: "allstren", namesByDeck: { Taldain: "Allstren Cynder" } },
    { id: "acron", namesByDeck: { Taldain: "Jon Acron" } },
    { id: "traiben", namesByDeck: { Taldain: "Traiben" } },
    { id: "drile", namesByDeck: { Taldain: "Drile" } },
    { id: "daazk", namesByDeck: { Taldain: "Daazk" } },
    { id: "gevalden", namesByDeck: { Taldain: "Gevalden" } },
    { id: "skathan", namesByDeck: { Taldain: "Skathan" } },
    { id: "dirin", namesByDeck: { Taldain: "Dirin" } },
    { id: "praxton", namesByDeck: { Taldain: "Praxton" } },
    { id: "elorin", namesByDeck: { Taldain: "Elorin" } },
    { id: "aarik", namesByDeck: { Taldain: "Aarik" } },
    { id: "heelis", namesByDeck: { Taldain: "Lady Judge Heelis" } },
    { id: "vey", namesByDeck: { Taldain: "Lord Merchant Vey" } },
    { id: "gennel", namesByDeck: { Taldain: "Lord Farmer Gennel" } },
    { id: "delius", namesByDeck: { Taldain: "Lord Admiral Delius" } },
    { id: "raagent", namesByDeck: { Taldain: "Lord General Raagent" } },
    { id: "rite", namesByDeck: { Taldain: "Lord Artisan Rite" } },
    { id: "ladymason", namesByDeck: { Taldain: "Lady Mason" } },
    { id: "ais", namesByDeck: { Taldain: "Ais" } },
    { id: "tain", namesByDeck: { Taldain: "Tain" } },
    { id: "mellis", namesByDeck: { Taldain: "Mellis" } },
    { id: "trell", namesByDeck: { Taldain: "Trell" } },

    { id: "vahr", namesByDeck: { Nalthis: "Vahr" } },
    { id: "susebron", namesByDeck: { Nalthis: "Susebron the Fifth" }, image: "images/susebron.png" },
    { id: "dedelin", namesByDeck: { Nalthis: "Dedelin" } },
    { id: "sisirinah", namesByDeck: { Nalthis: "Siri" }, image: "images/siri.png" },
    { id: "fafen", namesByDeck: { Nalthis: "Fafen" } },
    { id: "ridger", namesByDeck: { Nalthis: "Ridger" } },
    { id: "lightsong", namesByDeck: { Nalthis: "Lightsong the Bold" }, image: "images/lightsong.png" },
    { id: "llarimar", namesByDeck: { Nalthis: "Llarimar" }, image: "images/llarimar.png" },
    { id: "treledees", namesByDeck: { Nalthis: "Treledees" } },
    { id: "bluefingers", namesByDeck: { Nalthis: "Bluefingers" }, image: "images/bluefingers.png" },
    { id: "blushweaver", namesByDeck: { Nalthis: "Blushweaver the Beautiful" }, image: "images/blushweaver.png" },
    { id: "parlin", namesByDeck: { Nalthis: "Parlin" }, image: "images/parlin.png" },
    { id: "tonk", namesByDeck: { Nalthis: "Tonk Fah" }, image: "images/tonk.png" },
    { id: "lemex", namesByDeck: { Nalthis: "Lemex" } },
    { id: "jewels", namesByDeck: { Nalthis: "Jewels" }, image: "images/jewels.png" },
    { id: "arsteel", namesByDeck: { Nalthis: "Clod", Worldhoppers: "Arsteel" } },
    { id: "grable", namesByDeck: { Nalthis: "Grable" } },
    { id: "allmother", namesByDeck: { Nalthis: "Allmother" } },
    { id: "hopefinder", namesByDeck: { Nalthis: "Hopefinder the Just" } },
    { id: "rira", namesByDeck: { Nalthis: "Rira" } },
    { id: "ashu", namesByDeck: { Nalthis: "Ashu" } },
    { id: "vo", namesByDeck: { Nalthis: "Vo" } },
    { id: "chapps", namesByDeck: { Nalthis: "Old Chapps" } },
    { id: "tatara", namesByDeck: { Nalthis: "Tatara" } },

    { id: "tress", namesByDeck: { Lumar: "Tress" } },
    { id: "charlie", namesByDeck: { Lumar: "Charlie" } },
    { id: "lem", namesByDeck: { Lumar: "Lem" } },
    { id: "ulba", namesByDeck: { Lumar: "Ulba" } },
    { id: "verdant", namesByDeck: { Lumar: "Verdant King" } },
    { id: "crow", namesByDeck: { Lumar: "Crow", Emberdark: "Crow", Worldhoppers: "Crow" } },
    { id: "pakson", namesByDeck: { Lumar: "Pakson" } },
    { id: "fort", namesByDeck: { Lumar: "Fort" } },
    { id: "salay", namesByDeck: { Lumar: "Salay" } },
    { id: "doug1", namesByDeck: { Lumar: "Doug" } },
    { id: "doug2", namesByDeck: { Lumar: "Doug" } },
    { id: "doug3", namesByDeck: { Lumar: "Doug" } },
    { id: "doug4", namesByDeck: { Lumar: "Doug" } },
    { id: "doug5", namesByDeck: { Lumar: "Doug" } },
    { id: "doug6", namesByDeck: { Lumar: "Doug" } },
    { id: "doug7", namesByDeck: { Lumar: "Doug" } },
    { id: "doug8", namesByDeck: { Lumar: "Doug" } },
    { id: "doug9", namesByDeck: { Lumar: "Doug" } },
    { id: "doug10", namesByDeck: { Lumar: "Doug" } },
    { id: "doug11", namesByDeck: { Lumar: "Doug" } },
    { id: "doug12", namesByDeck: { Lumar: "Doug" } },
    { id: "doug13", namesByDeck: { Lumar: "Doug" } },
    { id: "doug14", namesByDeck: { Lumar: "Doug" } },
    { id: "doug15", namesByDeck: { Lumar: "Doug" } },
    { id: "doug16", namesByDeck: { Lumar: "Doug" } },
    { id: "laggart", namesByDeck: { Lumar: "Laggart" } },
    { id: "ann", namesByDeck: { Lumar: "Ann" } },
    { id: "xisisrefliel", namesByDeck: { Lumar: "Xisis", Emberdark: "Foil", Yolen: "Xisisrefliel" } },

    { id: "nikaro", namesByDeck: { Komashi: "Nikaro the Nightmare Painter" } },
    { id: "akane", namesByDeck: { Komashi: "Akane" } },
    { id: "tojin", namesByDeck: { Komashi: "Tojin" } },
    { id: "virtuosity", namesByDeck: { Komashi: "Virtuosity", Yolen: "Virtuosity", Shards: "Virtuosity", Emberdark: "Virtuosity" } },
    { id: "yumi", namesByDeck: { Komashi: "Yumi" } },
    { id: "liyun", namesByDeck: { Komashi: "Liyun" } },
    { id: "masaka", namesByDeck: { Komashi: "Masaka", Worldhoppers: "Chinikdakordich" } },
    { id: "izumakamo", namesByDeck: { Komashi: "Izumakamo" } },
    { id: "gyundok", namesByDeck: { Komashi: "Gyundok" } },
    { id: "sunjun", namesByDeck: { Komashi: "Sunjun" } },
    { id: "honam", namesByDeck: { Komashi: "Honam" } },
    { id: "nightmaremachine", namesByDeck: { Komashi: "The Machine" } },

    { id: "cinderking", namesByDeck: { Canticle: "Cinder King" } },
    { id: "elegy", namesByDeck: { Canticle: "Elegy Salvage" } },
    { id: "thomos", namesByDeck: { Canticle: "Thomos" } },
    { id: "divinity", namesByDeck: { Canticle: "Divinity Salvage" } },
    { id: "rebeke", namesByDeck: { Canticle: "Rebeke Salvage" } },
    { id: "zeal", namesByDeck: { Canticle: "Zeal" } },
    { id: "awrope", namesByDeck: { Canticle: "Adonalsium-Will-Remember-Our-Plight-Eventually" } },
    { id: "confidence", namesByDeck: { Canticle: "Confidence" } },
    { id: "compassion", namesByDeck: { Canticle: "Compassion" } },
    { id: "contemplation", namesByDeck: { Canticle: "Contemplation" } },
    { id: "jeffrey", namesByDeck: { Canticle: "Jeffrey Jeffrey" } },
    { id: "zellion", namesByDeck: { Canticle: "Zellion", Threnody: "Zellion", Worldhoppers: "Zellion" } },
    { id: "solemnity", namesByDeck: { Canticle: "Solemnity Divine" } },
    { id: "deborah", namesByDeck: { Canticle: "Deborah-James" } },
    { id: "truth", namesByDeck: { Canticle: "Truth-Is-Waiting" } },
    { id: "admiral", namesByDeck: { Canticle: "The Admiral" } },

    { id: "illistandrista", namesByDeck: { Emberdark: "Starling", Yolen: "Illistandrista", Worldhoppers: "Starling" } },
    { id: "sixth", namesByDeck: { Emberdark: "Sixth of the Dusk", Worldhoppers: "Sixth of the Dusk" }, image: "images/dusk.png" },
    { id: "kokerlii", namesByDeck: { Emberdark: "Kokerlii" } },
    { id: "sak", namesByDeck: { Emberdark: "Sak" } },
    { id: "vathi", namesByDeck: { Emberdark: "Vathi" }, image: "images/vathi.png" },
    { id: "patji", namesByDeck: { Emberdark: "Patji" } },
    { id: "cakoban", namesByDeck: { Emberdark: "Cakoban", Worldhoppers: "Cakoban" } },
    { id: "dakwara", namesByDeck: { Emberdark: "Dakwara" } },
    { id: "mirris", namesByDeck: { Emberdark: "Mirris" } },
    { id: "eusto", namesByDeck: { Emberdark: "Captain Eusto" } },
    { id: "aditil", namesByDeck: { Emberdark: "Aditil", Worldhoppers: "Aditil" } },
    { id: "zeetzi", namesByDeck: { Emberdark: "ZeetZi", Worldhoppers: "ZeetZi" } },
    { id: "chrysalis", namesByDeck: { Emberdark: "Chrysalis", Worldhoppers: "Chrysalis" } },
    { id: "leonore", namesByDeck: { Emberdark: "Leonore", Worldhoppers: "Leonore" } },
    { id: "dajer", namesByDeck: { Emberdark: "Dajer", Worldhoppers: "Dajer" } },
    { id: "tague", namesByDeck: { Emberdark: "Tague", Worldhoppers: "Tague" } }
];
